spring.application.name=speakly_bank
spring.flyway.locations=classpath:db/migration
spring.datasource.url=jdbc:mariadb://localhost:3306/speakly_bank?useSSL=false&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=root
server.port=8080